CREATE TABLE Usuarios (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(30) NOT NULL,
    email VARCHAR(50),
    senha VARCHAR(255) NOT NULL,
    funcao VARCHAR(20) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Produtos (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    image_path VARCHAR(255),
    descricao TEXT,
    categoria_id INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (categoria_id) REFERENCES Categorias(id),
    preco DECIMAL(10, 2) NOT NULL,
    estoque INT(11) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Pedidos (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    usuario_id INT(6) UNSIGNED NOT NULL,
    data_pedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL,
    total DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (usuario_id) REFERENCES Usuarios(id)
);

CREATE TABLE ItensPedido (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    pedido_id INT(6) UNSIGNED NOT NULL,
    produto_id INT(6) UNSIGNED NOT NULL,
    quantidade INT(11) NOT NULL,
    preco_unitario DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (pedido_id) REFERENCES Pedidos(id),
    FOREIGN KEY (produto_id) REFERENCES Produtos(id)
);

CREATE TABLE Pagamentos (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    pedido_id INT(6) UNSIGNED NOT NULL,
    metodo_pagamento VARCHAR(50) NOT NULL,
    status_pagamento VARCHAR(20) NOT NULL,
    data_pagamento TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (pedido_id) REFERENCES Pedidos(id)
);

CREATE TABLE Categorias (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    descricao TEXT,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Carrinhos (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    usuario_id INT(6) UNSIGNED NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES Usuarios(id)
);

CREATE TABLE ItensCarrinho (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    carrinho_id INT(6) UNSIGNED NOT NULL,
    produto_id INT(6) UNSIGNED NOT NULL,
    quantidade INT(11) NOT NULL,
    preco_unitario DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (carrinho_id) REFERENCES Carrinhos(id),
    FOREIGN KEY (produto_id) REFERENCES Produtos(id)
);

